#!/bin/sh
#
# $FreeBSD$

set -e
set -u

. "$MUNIN_LIBDIR/plugins/plugin.sh"

cat <<'EOM'
graph_title ZFS dataset error counters
graph_vlabel amount of errors
graph_category fs
graph_info This graph shows the ZFS dataset error counters for reads, writes, and checksums
EOM

status=$(zpool status|awk 'BEGIN {p=0} /spares$/ || /^$/ {p=0} p==1 {print} /NAME.*STATE.*READ/ {p=1}')

while read -r label _ r w c; do
	field=$( clean_fieldname "${label}" )
	echo "R${field}.label ${label} READ"
	echo "R${field}.value ${r}"
	echo "R${field}.warning 1"
	echo "R${field}.critical 2"
	echo "W${field}.label ${label} WRITE"
	echo "W${field}.value ${w}"
	echo "W${field}.warning 1"
	echo "W${field}.critical 2"
	echo "C${field}.label ${label} CHKSUM"
	echo "C${field}.value ${c}"
	echo "C${field}.warning 1"
	echo "C${field}.critical 2"
done <<eot
${status}
eot

exit 0
