#!/bin/sh

# Plugin to monitor specific S.M.A.R.T. attributes of Plextor PX-G128M6e with smartctl command

id=${0##*g128m6e_}

# id
## 177: Wear_Leveling_Count => RAW_VALUE count
## 241: Total_LBAs_Written  => RAW_VALUE * 32 MiB
## 242: Total_LBAs_Read => RAW_VALUE * 32 MiB

if [ -z "${id}" ]; then
    echo 'plugin filename is wrong. it should be g128m6e_`id`' >&2
    exit 1
fi

if [ ! -b "${device}" ]; then
    echo "${device} is not a device." >&2
    exit 1
fi

if [ "$(id -u)" != "0" ]; then
    echo "this plugin need 'user root' to run" >&2
    exit 1
fi

line=$(/usr/bin/smartctl -A ${device} | /usr/bin/grep "${id}")
if [ -z "${line}" ]; then
    echo "cannot retrieve value from ${device}" >&2
    exit 1
fi

name=$(echo ${line} | cut -d' ' -f2)
value=$(echo ${line} | cut -d' ' -f10)

if [ "$1" = "config" ]; then
    echo "graph_title ${name} (${id})"
    if [ "${id}" = "177" ]; then
        echo "graph_args --base 1000"
        echo "graph_vlabel counts"
    else
        # RAW_VALUE * 32 MiB * 1024^2
        echo "graph_args --base 1024"
        echo "graph_vlabel bytes"
    fi
    echo "graph_info This graph monitors specific S.M.A.R.T. attributes of Plextor PX-G128M6e"
    echo "graph_category plextor"

    echo "id${id}.label ${name}"
    echo "id${id}.type GAUGE"
    echo "id${id}.min 0"
    exit 0
fi

## output value

if [ "${id}" != "177" ]; then
    # RAW_VALUE * 32 MiB * 1024^2
    value=$(expr ${value} \* 32 \* 1024 \* 1024)
fi

echo "id${id}.value ${value}"
