#!/bin/sh

# Wildcard plugin to monitor specific S.M.A.R.T. attributes of Seagate HDD with smartctl command

id=${0##*seagate_}

# id
## 241: Total_LBAs_Written  => RAW_VALUE * 512 Bytes
## 242: Total_LBAs_Read => RAW_VALUE * 512 Bytes

if [ -z "${id}" ]; then
    echo 'plugin filename is wrong. it should be seagate_`id`' >&2
    exit 1
fi

if [ ! -b "${device}" ]; then
    echo "${device} is not a device." >&2
    exit 1
fi

if [ "$(id -u)" != "0" ]; then
    echo "this plugin need 'root' privilege to run" >&2
    exit 1
fi

model=$(/usr/bin/smartctl -i ${device} | grep "Device Model:" | cut -d':' -f2)
line=$(/usr/bin/smartctl -A ${device} | grep "${id}")
if [ -z "${line}" ]; then
    echo "cannot retrieve value from ${device}" >&2
    exit 1
fi

name=$(echo ${line} | cut -d' ' -f2)
value=$(echo ${line} | cut -d' ' -f10)

if [ "$1" = "config" ]; then
    echo "graph_title ${id}: ${name}"
    # RAW_VALUE * 512 Bytes
    echo "graph_args --base 1024"
    echo "graph_vlabel bytes"
    echo "graph_info This graph shows the value of specific S.M.A.R.T. attributes of ${model} (${device})"
    echo "graph_category smart"

    echo "id${id}.label ${name}"
    echo "id${id}.type GAUGE"
    echo "id${id}.min 0"
    exit 0
fi

## output value

# RAW_VALUE * 512 Bytes
value=$(expr ${value} \* 512)

echo "id${id}.value ${value}"
