#!/bin/sh

case $1 in
    config)
        cat <<'EOM'

graph_title Temperatures
graph_vlabel degrees Celsius
graph_args --base 1000 -l 0
graph_category sensors
temp.label BCM2835
temp.warning 60
temp.critical 85

EOM
        exit 0
        ;;
esac

if [ -x /opt/vc/bin/vcgencmd ]; then
    CMD="/opt/vc/bin/vcgencmd"
elif [ -x /usr/bin/vcgencmd ]; then
    CMD="/usr/bin/vcgencmd"
else
    >&2 echo "$0: vcgencmd executable was not found."
    exit 1
fi

echo -n "temp.value "
$CMD measure_temp | cut -d "=" -f2 | cut -d "'" -f1
