#!/bin/sh

target_lists='arm core h264 isp v3d uart pwm emmc pixel vec hdmi dpi'

case $1 in
    config)
        cat <<'EOM'

graph_title Clock frequencies
graph_vlabel Hz
graph_args --base 1000 -l 0
graph_category sensors
EOM

for target in $target_lists; do
    echo $target.label $target
done
        exit 0
        ;;
esac

for target in $target_lists; do
    echo -n "$target.value "
    /opt/vc/bin/vcgencmd measure_clock $target | cut -d "=" -f2
done
