#!/bin/sh

target_lists='core sdram_c sdram_i sdram_p'

case $1 in
    config)
        cat <<'EOM'

graph_title Voltages
graph_vlabel V
graph_args --base 1000 -l 0
graph_category sensors
EOM

for target in $target_lists; do
    echo $target.label $target
done
        exit 0
        ;;
esac

for target in $target_lists; do
    echo -n "$target.value "
    /opt/vc/bin/vcgencmd measure_volts $target | cut -d "=" -f2 | cut -d "V" -f1
done
