#!/bin/sh

target_lists='core sdram_c sdram_i sdram_p'

case $1 in
    config)
        cat <<'EOM'

graph_title Voltages
graph_vlabel V
graph_args --base 1000 -l 0
graph_category sensors
EOM

for target in $target_lists; do
    echo $target.label $target
done
        exit 0
        ;;
esac

if [ -x /opt/vc/bin/vcgencmd ]; then
    CMD="/opt/vc/bin/vcgencmd"
elif [ -x /usr/bin/vcgencmd ]; then
    CMD="/usr/bin/vcgencmd"
else
    >&2 echo "$0: vcgencmd executable was not found."
    exit 1
fi

for target in $target_lists; do
    echo -n "$target.value "
    $CMD measure_volts $target | cut -d "=" -f2 | cut -d "V" -f1
done
