#!/bin/sh

set -u

usage () {
    cat <<'EOF'
usage: $0 -l device list file

 -l: specify file path for device list

EOF
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

warn () {
    >&2 echo "$0: $@"
}

isexist () {
    [ -e "$1" ] && return 0
    warn "$1 does not exist"
    exit 1
}


# parse commandline arguments
while getopts "l:p:d:r:" OPT; do
    case $OPT in
        l)  LISTPATH="$OPTARG"
            isexist "$LISTPATH"
            ;;
    esac
done
shift $(( $OPTIND - 1 ))


# read sensor device list from LISTPATH and execute bluetoothctl connect for each device
ret=0
while IFS='' read -r line || [[ -n "$line" ]]
do
    device=$(echo "$line" | cut -d' ' -f1)
    echo connect $device | /usr/bin/bluetoothctl

    # check each return code to final result
    __ret=$?
    if [ $__ret -ne 0 ]; then
        ret=$__ret
    fi
done < $LISTPATH


if [ $ret -ne 0 ]; then
    warn "something wrong on execution"
    exit $ret
fi
